### ISSUE TITLE
Handling Variables in Images eg: Database Password

### ISSUE THREAD

**Issue by tschettervictor** [DtxdF/reproduce#1]
If one reproduces an image, is the image then set in stone with a certain password?

Examples include apps requiring databases.

Is the database password (and other such variables) changeable with each deployment of said image?

Say I deploy an image someone else has created, is the password already set or…?

**Comment by DtxdF** [comment]
You should not build an image based on your deployment because it may or may not contain sensitive data (although many Makejails separate this using volumes). But even without containing sensitive information a deployment may assume that some data must be on a certain path within the jail, so if you deploy an image that does not contain such data, it will probably fail. Examples of the latter case are Nextcloud and MariaDB.

This is the reason why I separate `Makejail` and `build.makejail`, so you should only share your image based on `build.makejail`, not `Makejail`. The [repository](https://github.com/DtxdF/reproduce-projects) containing the configuration files builds only `build.makejail`, so it is safe to share the image.
